apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gosimplehttp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/zufardhiyaulhaq/argocd-github-actions.git
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default